# Proxy_path = /afs/cern.ch/user/y/yelberke/private/cert
executable            = scripts/reco_wrap.sh
arguments             = $(input_dir) $(analysisworkspace)/$(analysisname)/intermediate_prot/$(input_dir) $(Proxy_path) $(cmsworkpath)

output                = output/$(ProcId).out
error                 = error/$(ProcId).err
log                   = log/$(ProcId)_condor.log

transfer_input_files  = ./scripts/run_reco.sh

RequestCpus = 10

queue input_dir from $(filelist)
